server:
  port: 7001

# Eureka
eureka:
  instance:
    hostname: eureka7001.com # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向注册中心注册自己，自己本身为服务器不需要
    fetch-registry: false # false：表示自己为注册中心
    # 监控页面
    service-url:
      # 默认："defaultZone", "http://localhost:8761/eureka/"
      # （单机）注册地址 http://${eureka.instance.hostname}:${server.port}/eureka/
      # 监控地址 http://${eureka.instance.hostname}:${server.port}
      # （单机）defaultZone: http://${eureka.instance.hostname}:${server.port}/defaultZone/

      # 集群(关联)
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/